[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["-C", "default-linker-libraries"]

[build]
target = "riscv32imac-esp-espidf"
rustflags = ["-Z", "build-std"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v5.1.3"
MCU = "esp32c6"
