//! Byte-exactness tests against golden vectors generated by the Python
//! LXMF reference implementation (`fixtures/generate.py`).

use lxmf::fields::*;
use lxmf::router::{DeliveryConfig, LxmEvent, LxmRouter, RouterConfig};
use lxmf::stamper;
use lxmf::*;
use rand_core::OsRng;
use reticulum::hash::AddressHash;
use reticulum::identity::PrivateIdentity;
use reticulum::transport::{Transport, TransportConfig};

fn golden() -> serde_json::Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/golden.json");
    serde_json::from_str(&std::fs::read_to_string(path).expect("golden.json present"))
        .expect("valid json")
}

fn hex(s: &str) -> Vec<u8> {
    from_hex(s).expect("valid hex")
}

fn fixed_identity(key_hex: &str) -> PrivateIdentity {
    PrivateIdentity::new_from_hex_string(key_hex).expect("valid identity")
}

/// Unpack the first binary element of a propagation container
/// (`[time, [lxm_data]]`), returning the raw transport bytes.
fn propagation_container_lxmf_data(container: &[u8]) -> Vec<u8> {
    let mut rd: &[u8] = container;
    let value = FieldValue::unpack(&mut rd).expect("container");
    let FieldValue::Array(items) = value else {
        panic!("container must be an array")
    };
    assert!(items[0].as_f64().is_some(), "container time must be a float");
    let FieldValue::Array(inner) = &items[1] else {
        panic!("container messages must be an array")
    };
    let FieldValue::Bin(data) = &inner[0] else {
        panic!("container message must be binary")
    };
    data.clone()
}

/// Convert the tagged JSON representation used by the fixture generator
/// into a [`FieldValue`].
fn value_from_json(value: &serde_json::Value) -> FieldValue {
    let tag = value[0].as_str().expect("tagged value");
    match tag {
        "nil" => FieldValue::Nil,
        "bool" => FieldValue::Bool(value[1].as_bool().expect("bool")),
        "int" => FieldValue::Int(value[1].as_i64().expect("int")),
        "float" => FieldValue::F64(value[1].as_f64().expect("float")),
        "str" => FieldValue::Str(value[1].as_str().expect("str").to_string()),
        "bin" => FieldValue::Bin(hex(value[1].as_str().expect("bin hex"))),
        "list" => FieldValue::Array(
            value[1]
                .as_array()
                .expect("list")
                .iter()
                .map(value_from_json)
                .collect(),
        ),
        "map" => FieldValue::Map(
            value[1]
                .as_array()
                .expect("map entries")
                .iter()
                .map(|entry| (value_from_json(&entry[0]), value_from_json(&entry[1])))
                .collect(),
        ),
        other => panic!("unknown tag {other}"),
    }
}

fn fields_from_json(value: &serde_json::Value) -> Fields {
    Fields::from_value(&value_from_json(value)).expect("valid fields")
}

/// Recreate a packed message from a fixture, byte-for-byte.
fn pack_fixture_message(
    fixture: &serde_json::Value,
    source: &PrivateIdentity,
    stamp: Option<Vec<u8>>,
    desired_method: Option<u8>,
) -> LXMessage {
    let destination_hash = AddressHash::new(
        hex(fixture["destination_hash"].as_str().unwrap())
            .try_into()
            .unwrap(),
    );
    let source_hash =
        AddressHash::new(hex(fixture["source_hash"].as_str().unwrap()).try_into().unwrap());

    let mut message = LXMessage::new(
        destination_hash,
        source_hash,
        &hex(fixture["title"].as_str().unwrap()),
        &hex(fixture["content"].as_str().unwrap()),
    );
    message.set_fields(fields_from_json(&fixture["fields"]));
    message.timestamp = Some(fixture["timestamp"].as_f64().unwrap());
    if let Some(stamp) = stamp {
        message.stamp = Some(stamp);
        message.stamp_cost = Some(8);
        message.defer_stamp = false;
    }
    message.desired_method = desired_method;
    message.pack(source).expect("pack");
    message
}

#[test]
fn identities_match_python() {
    let g = golden();
    for (name, entry) in g["identities"].as_object().unwrap() {
        let identity = fixed_identity(entry["private_hex"].as_str().unwrap());
        assert_eq!(
            to_hex(identity.address_hash().as_slice()),
            entry["hash"].as_str().unwrap(),
            "identity hash mismatch for {name}"
        );

        let public = identity.as_identity();
        let mut public_hex = String::new();
        public_hex.push_str(&to_hex(public.public_key_bytes()));
        public_hex.push_str(&to_hex(public.verifying_key_bytes()));
        assert_eq!(public_hex, entry["public_hex"].as_str().unwrap());

        // Destination hashes ("lxmf.delivery" / "lxmf.propagation")
        if let Some(delivery) = entry["delivery_destination_hash"].as_str() {
            assert_eq!(
                to_hex(delivery_destination_hash(public).as_slice()),
                delivery
            );
        }
        if let Some(propagation) = entry["propagation_destination_hash"].as_str() {
            assert_eq!(
                to_hex(propagation_destination_hash(public).as_slice()),
                propagation
            );
        }
    }
}

#[test]
fn packed_messages_match_python_bytes() {
    let g = golden();
    let source = fixed_identity(g["identities"]["source"]["private_hex"].as_str().unwrap());

    for fixture in g["messages"].as_array().unwrap() {
        let name = fixture["name"].as_str().unwrap();
        let stamp = fixture["stamp"].as_str().map(hex);

        let message = pack_fixture_message(fixture, &source, stamp, None);

        let packed = message.packed.as_ref().expect("packed");
        assert_eq!(
            to_hex(packed),
            fixture["packed"].as_str().unwrap(),
            "packed bytes mismatch for message {name}"
        );
        assert_eq!(
            message.packed_size,
            Some(fixture["packed_size"].as_u64().unwrap() as usize)
        );
        assert_eq!(
            to_hex(message.hash.unwrap().as_slice()),
            fixture["hash"].as_str().unwrap(),
            "hash mismatch for message {name}"
        );
        assert_eq!(
            to_hex(message.signature.unwrap().as_ref()),
            fixture["signature"].as_str().unwrap(),
            "signature mismatch for message {name}"
        );
        assert_eq!(
            message.method as u64,
            fixture["method"].as_u64().unwrap(),
            "method mismatch for message {name}"
        );
        assert_eq!(
            message.representation as u64,
            fixture["representation"].as_u64().unwrap(),
            "representation mismatch for message {name}"
        );
    }
}

#[test]
fn unpack_python_bytes() {
    let g = golden();
    let source_identity = *fixed_identity(g["identities"]["source"]["private_hex"].as_str().unwrap())
        .as_identity();
    let source_hash = AddressHash::new(
        hex(g["identities"]["source"]["delivery_destination_hash"]
            .as_str()
            .unwrap())
        .try_into()
        .unwrap(),
    );

    for fixture in g["messages"].as_array().unwrap() {
        let name = fixture["name"].as_str().unwrap();
        let packed = hex(fixture["packed"].as_str().unwrap());

        // Without any known identities the signature is unverified with
        // SOURCE_UNKNOWN (mirrors unpack_from_bytes without recalls).
        let unverified = LXMessage::unpack_from_bytes(&packed).expect("unpack");
        assert!(!unverified.signature_validated);
        assert_eq!(unverified.unverified_reason, Some(SOURCE_UNKNOWN), "{name}");
        assert_eq!(unverified.title, hex(fixture["title"].as_str().unwrap()));
        assert_eq!(
            unverified.content,
            hex(fixture["content"].as_str().unwrap())
        );
        assert_eq!(
            unverified.timestamp,
            Some(fixture["timestamp"].as_f64().unwrap())
        );
        assert_eq!(
            to_hex(unverified.hash.unwrap().as_slice()),
            fixture["hash"].as_str().unwrap()
        );
        assert_eq!(
            unverified.get_fields(),
            &fields_from_json(&fixture["fields"]),
            "fields mismatch for {name}"
        );

        // With the source identity recalled, the signature validates.
        let verified = LXMessage::unpack_from_bytes_with(&packed, &|hash| {
            (hash == &source_hash).then_some(source_identity)
        })
        .expect("unpack");
        assert!(verified.signature_validated, "{name}");
        assert_eq!(verified.unverified_reason, None);
        assert_eq!(verified.stamp.map(|s| to_hex(&s)).as_deref(), fixture["stamp"].as_str());

        // A mutated payload must fail signature validation (or fail to
        // parse entirely, which the Python router treats identically).
        // Note that flipping a stamp byte would NOT invalidate anything,
        // since the stamp is not covered by the signature; mutate the
        // first title byte instead (byte 96 + 9 = after the payload array
        // header and the float64 timestamp).
        let mut corrupted = packed.clone();
        corrupted[DESTINATION_LENGTH * 2 + SIGNATURE_LENGTH + 9] ^= 0x01;
        if let Ok(invalid) = LXMessage::unpack_from_bytes_with(&corrupted, &|hash| {
            (hash == &source_hash).then_some(source_identity)
        }) {
            assert!(!invalid.signature_validated, "{name}");
            assert_eq!(invalid.unverified_reason, Some(SIGNATURE_INVALID), "{name}");
        }

        // Flipping a signature byte always yields a parseable message with
        // an invalid signature.
        let mut bad_signature = packed.clone();
        bad_signature[2 * 16 + 8] ^= 0xFF;
        let invalid = LXMessage::unpack_from_bytes_with(&bad_signature, &|hash| {
            (hash == &source_hash).then_some(source_identity)
        })
        .expect("unpack");
        assert!(!invalid.signature_validated, "{name}");
        assert_eq!(invalid.unverified_reason, Some(SIGNATURE_INVALID), "{name}");
    }
}

#[test]
fn packed_container_matches_python() {
    let g = golden();
    let source = fixed_identity(g["identities"]["source"]["private_hex"].as_str().unwrap());
    let fixture = g["messages"]
        .as_array()
        .unwrap()
        .iter()
        .find(|m| m["name"] == "small")
        .unwrap();

    let mut message = pack_fixture_message(fixture, &source, None, None);
    let container = message.packed_container().expect("container");
    assert_eq!(
        to_hex(&container),
        g["packed_container"]["bytes"].as_str().unwrap()
    );
}

#[test]
fn ticket_stamp_validates() {
    let g = golden();
    let source = fixed_identity(g["identities"]["source"]["private_hex"].as_str().unwrap());
    let fixture = g["messages"]
        .as_array()
        .unwrap()
        .iter()
        .find(|m| m["name"] == "ticket")
        .unwrap();

    let message = pack_fixture_message(
        fixture,
        &source,
        fixture["stamp"].as_str().map(hex),
        None,
    );
    let ticket = hex(fixture["ticket"].as_str().unwrap());
    let ticket_bytes: [u8; TICKET_LENGTH] = ticket.try_into().unwrap();

    // With the ticket presented, the stamp validates at COST_TICKET value.
    let mut message = message;
    assert!(message.validate_stamp(Some(8), Some(&[ticket_bytes])));
    assert_eq!(message.stamp_value, Some(COST_TICKET));

    // Without it, the ticket-derived stamp does not validate as work.
    let mut message2 = pack_fixture_message(fixture, &source, None, None);
    assert!(!message2.validate_stamp(Some(32), Some(&[])));
}

#[test]
fn stamps_match_python() {
    let g = golden();

    for fixture in g["stamps"].as_array().unwrap() {
        let message_id = hex(fixture["message_id"].as_str().unwrap());
        let stamp = hex(fixture["stamp"].as_str().unwrap());
        let cost = fixture["cost"].as_u64().unwrap() as u32;
        let expand_rounds = fixture["expand_rounds"].as_u64().unwrap() as usize;

        let workblock = stamper::stamp_workblock_with_rounds(&message_id, expand_rounds);
        if let Some(expected_len) = fixture["workblock_len"].as_u64() {
            assert_eq!(
                workblock.len(),
                expected_len as usize,
                "workblock length mismatch"
            );
        }
        if let Some(expected_hash) = fixture["workblock_hash"].as_str() {
            assert_eq!(to_hex(full_hash(&workblock).as_slice()), expected_hash);
        }

        assert!(
            stamper::stamp_valid(&stamp, cost, &workblock),
            "python stamp must validate at cost {cost}"
        );
        assert_eq!(
            stamper::stamp_value(&workblock, &stamp),
            fixture["value"].as_u64().unwrap(),
            "stamp value mismatch"
        );

        // Above the found work value the stamp must be rejected.
        let value = fixture["value"].as_u64().unwrap() as u32;
        assert!(!stamper::stamp_valid(&stamp, value + 1, &workblock));
    }
}

#[test]
fn generate_stamp_and_validate() {
    // Fast work block for generation testing
    let material = [7u8; 32];
    let (stamp, value) = stamper::generate_stamp_with_rounds(
        &material,
        8,
        stamper::WORKBLOCK_EXPAND_ROUNDS_PEERING,
        &mut OsRng,
    );
    let stamp = stamp.expect("stamp generated");
    assert!(value >= 8);

    let workblock = stamper::stamp_workblock_with_rounds(
        &material,
        stamper::WORKBLOCK_EXPAND_ROUNDS_PEERING,
    );
    assert!(stamper::stamp_valid(&stamp, 8, &workblock));
    assert_eq!(stamper::stamp_value(&workblock, &stamp), value);

    // Cross-check the peering key validation path
    assert!(stamper::validate_peering_key(&material, &stamp, 8));
    assert!(!stamper::validate_peering_key(&material, &stamp, 20));
}

#[test]
fn validate_pn_stamp_roundtrip() {
    // Build a transient entry the way a propagation node client would:
    // lxm_data || stamp, where the stamp is found over the transient id
    // (the full hash of lxm_data) with PN work block expansion.
    // Realistic size: the Python implementation rejects transport data at
    // or below LXMF_OVERHEAD + STAMP_SIZE bytes.
    let lxm_data = [0xAAu8; 200];
    let transient_id = full_hash(&lxm_data);

    let (stamp, value) = stamper::generate_stamp_with_rounds(
        transient_id.as_slice(),
        8,
        stamper::WORKBLOCK_EXPAND_ROUNDS_PN,
        &mut OsRng,
    );
    let stamp = stamp.expect("pn stamp");
    assert!(value >= 8);

    let mut transient_data = lxm_data.to_vec();
    transient_data.extend_from_slice(&stamp);

    // The transient id is derived from the data without the stamp
    assert_eq!(full_hash(&lxm_data).as_slice(), transient_id.as_slice());

    let validated = stamper::validate_pn_stamp(&transient_data, 8).expect("valid pn stamp");
    assert_eq!(validated.transient_id.as_slice(), transient_id.as_slice());
    assert_eq!(validated.lxm_data, lxm_data);
    assert_eq!(validated.stamp.as_slice(), stamp.as_slice());
    assert_eq!(validated.value, value);

    // One above the found value rejects the stamp
    assert!(stamper::validate_pn_stamp(&transient_data, value as u32 + 1).is_none());

    // And data without room for a message is rejected outright
    assert!(stamper::validate_pn_stamp(&lxm_data, 8).is_none());
}

#[test]
fn peer_data_matches_python() {
    let g = golden();
    let bytes = hex(g["peer"]["bytes"].as_str().unwrap());

    let peer = PeerData::from_bytes(&bytes).expect("peer data");
    let repacked = peer.to_bytes();
    assert_eq!(to_hex(&repacked), to_hex(&bytes), "peer round-trip mismatch");

    // Spot-check parsed values against the fixture dictionary
    let expected = value_from_json(&g["peer"]["fields"]);
    let FieldValue::Map(entries) = expected else { unreachable!() };
    for (key, value) in entries {
        let Some(key) = key.as_str() else { continue };
        match key {
            "destination_hash" => {
                assert_eq!(peer.destination_hash.as_slice(), value.as_bin().unwrap())
            }
            "peering_timebase" => assert_eq!(peer.peering_timebase, value.as_int().unwrap()),
            "alive" => assert_eq!(peer.alive, matches!(value, FieldValue::Bool(true))),
            "last_heard" => assert_eq!(peer.last_heard, value.as_f64().unwrap()),
            "peering_cost" => assert_eq!(peer.peering_cost, Some(value.as_int().unwrap())),
            "propagation_transfer_limit" => {
                assert_eq!(peer.propagation_transfer_limit, value.as_f64())
            }
            "propagation_sync_limit" => {
                assert_eq!(peer.propagation_sync_limit, value.as_int())
            }
            "handled_ids" => {
                let FieldValue::Array(ids) = value else { unreachable!() };
                assert_eq!(peer.handled_ids.len(), ids.len());
            }
            "metadata" => {
                assert!(peer.metadata.is_some());
                assert_eq!(peer.name().as_deref(), Some("Test Node"));
            }
            "peering_key" => {
                let peering_key = peer.peering_key.as_ref().expect("peering key");
                assert_eq!(peering_key.value, 12);
                let FieldValue::Array(items) = value else { unreachable!() };
                assert_eq!(peering_key.stamp, items[0].as_bin().unwrap());
            }
            _ => {}
        }
    }
}

#[test]
fn announce_app_data_helpers() {
    let g = &golden()["announce_app_data"];

    let delivery = hex(g["delivery"].as_str().unwrap());
    assert_eq!(
        display_name_from_app_data(Some(&delivery)).as_deref(),
        Some(g["delivery_display_name"].as_str().unwrap())
    );
    assert_eq!(
        stamp_cost_from_app_data(Some(&delivery)),
        Some(g["delivery_stamp_cost"].as_u64().unwrap() as u8)
    );
    assert_eq!(
        compression_support_from_app_data(Some(&delivery)),
        g["delivery_compression_support"].as_bool().unwrap()
    );

    // Re-packing the delivery app data must reproduce the fixture bytes
    assert_eq!(
        to_hex(&pack_announce_app_data(
            Some(g["delivery_display_name"].as_str().unwrap()),
            Some(g["delivery_stamp_cost"].as_u64().unwrap() as u8),
            &[SF_COMPRESSION],
        )),
        g["delivery"].as_str().unwrap()
    );

    // Legacy (pre-0.5.0) announce format
    let legacy = hex(g["legacy_delivery"].as_str().unwrap());
    assert_eq!(
        display_name_from_app_data(Some(&legacy)).as_deref(),
        Some(g["legacy_delivery_display_name"].as_str().unwrap())
    );
    assert_eq!(stamp_cost_from_app_data(Some(&legacy)), None);

    // Propagation node data
    let pn = hex(g["propagation_node"].as_str().unwrap());
    assert!(pn_announce_data_is_valid(Some(&pn)));
    assert_eq!(
        pn_name_from_app_data(Some(&pn)).as_deref(),
        Some("Test Node")
    );
    assert_eq!(
        pn_stamp_cost_from_app_data(Some(&pn)),
        Some(g["pn_stamp_cost"].as_i64().unwrap())
    );

    let info = pn_announce_data_from_app_data(Some(&pn)).unwrap();
    assert_eq!(info.timebase, g["pn_timebase"].as_i64().unwrap());
    assert_eq!(info.node_state, g["pn_node_state"].as_bool().unwrap());
    assert_eq!(
        info.propagation_transfer_limit,
        g["pn_transfer_limit"].as_i64().unwrap()
    );
    assert_eq!(
        info.propagation_sync_limit,
        g["pn_sync_limit"].as_i64().unwrap()
    );
    assert_eq!(
        info.stamp_cost_flexibility,
        g["pn_stamp_cost_flexibility"].as_i64().unwrap()
    );
    assert_eq!(info.peering_cost, g["pn_peering_cost"].as_i64().unwrap());

    // Invalid data is rejected
    assert!(!pn_announce_data_is_valid(Some(&[])));
    assert!(!pn_announce_data_is_valid(Some(&[0x91, 0xc2])));
}

#[test]
fn paper_message_from_python_uri() {
    let g = golden();
    let paper = &g["paper"];
    let uri = paper["uri"].as_str().unwrap();

    let destination_identity =
        fixed_identity(g["identities"]["destination"]["private_hex"].as_str().unwrap());

    let paper_packed = hex(paper["paper_packed"].as_str().unwrap());

    // The URI must decode back into the exact packed paper message
    let decoded = lxmf::message::base64_urlsafe_decode(&uri["lxm://".len()..]).unwrap();
    assert_eq!(decoded, paper_packed);

    // And the transient id matches the full hash of the paper data
    assert_eq!(
        to_hex(full_hash(&decoded).as_slice()),
        paper["transient_id"].as_str().unwrap()
    );

    // Decrypting with the destination identity yields the original message
    let (message, transient_id) =
        LXMessage::unpack_from_uri(uri, &destination_identity, &|_| None).expect("unpack uri");
    assert_eq!(
        to_hex(transient_id.as_slice()),
        paper["transient_id"].as_str().unwrap()
    );
    assert_eq!(message.title, hex(paper["title"].as_str().unwrap()));
    assert_eq!(message.content, hex(paper["content"].as_str().unwrap()));
    assert_eq!(message.timestamp, Some(paper["timestamp"].as_f64().unwrap()));
    assert_eq!(message.method, UNKNOWN);
}

#[test]
fn paper_message_roundtrip_in_rust() {
    let g = golden();
    let source = fixed_identity(g["identities"]["source"]["private_hex"].as_str().unwrap());
    let destination_identity =
        fixed_identity(g["identities"]["destination"]["private_hex"].as_str().unwrap());
    let destination_public = *destination_identity.as_identity();
    let destination_hash = AddressHash::new(
        hex(g["identities"]["destination"]["delivery_destination_hash"]
            .as_str()
            .unwrap())
        .try_into()
        .unwrap(),
    );
    let source_hash = AddressHash::new(
        hex(g["identities"]["source"]["delivery_destination_hash"]
            .as_str()
            .unwrap())
        .try_into()
        .unwrap(),
    );

    let mut message = LXMessage::new(destination_hash, source_hash, b"Paper", b"Paper message");
    message.timestamp = Some(1735689600.5);
    message.destination_identity = Some(destination_public);
    message.pack_paper(&source, OsRng).expect("pack paper");

    assert_eq!(message.method, PAPER);
    assert_eq!(message.representation, PAPER);

    let uri = message.as_uri().expect("uri");
    assert!(uri.starts_with("lxm://"));
    assert!(!uri.contains('='));

    // Round-trip through the URI
    let (unpacked, _) =
        LXMessage::unpack_from_uri(&uri, &destination_identity, &|_| None).expect("unpack");
    assert_eq!(unpacked.title, b"Paper");
    assert_eq!(unpacked.content, b"Paper message");
    assert_eq!(unpacked.hash, message.hash);
    assert_eq!(unpacked.signature, message.signature);
}

#[test]
fn propagation_container_from_python() {
    let g = golden();
    let prop = &g["propagation"];

    let destination_identity =
        fixed_identity(g["identities"]["destination"]["private_hex"].as_str().unwrap());

    // Unpack the propagation container: [time, [lxm_data]]
    let packed = hex(prop["propagation_packed"].as_str().unwrap());
    let lxmf_data = propagation_container_lxmf_data(&packed);

    // The container data is destination hash + encrypted message
    assert_eq!(
        &lxmf_data[..16],
        hex(prop["destination_hash"].as_str().unwrap()).as_slice()
    );

    // And the transient id is the full hash of the container data
    assert_eq!(
        to_hex(full_hash(&lxmf_data).as_slice()),
        prop["transient_id"].as_str().unwrap()
    );

    // Decrypting the payload yields the original packed message tail
    let decrypted =
        lxmf::message::decrypt_for_identity(&destination_identity, &lxmf_data[16..])
            .expect("decrypt");
    let packed_message = hex(prop["packed"].as_str().unwrap());
    assert_eq!(decrypted.as_slice(), &packed_message[16..]);
}

#[test]
fn constants_match_python() {
    assert_eq!(APP_NAME, "lxmf");
    assert_eq!(DESTINATION_LENGTH, 16);
    assert_eq!(SIGNATURE_LENGTH, 64);
    assert_eq!(TICKET_LENGTH, 16);
    assert_eq!(LXMF_OVERHEAD, 112);
    assert_eq!(ENCRYPTED_PACKET_MDU, 391);
    assert_eq!(ENCRYPTED_PACKET_MAX_CONTENT, 295);
    assert_eq!(LINK_PACKET_MDU, 431);
    assert_eq!(LINK_PACKET_MAX_CONTENT, 319);
    assert_eq!(PLAIN_PACKET_MDU, 464);
    assert_eq!(PLAIN_PACKET_MAX_CONTENT, 368);
    assert_eq!(PAPER_MDU, 2210);
    assert_eq!(COST_TICKET, 0x100);
    assert_eq!(TICKET_EXPIRY, 21.0 * 24.0 * 60.0 * 60.0);
    assert_eq!(
        STATES,
        [
            GENERATING,
            OUTBOUND,
            SENDING,
            SENT,
            DELIVERED,
            REJECTED,
            CANCELLED,
            FAILED
        ]
    );
    assert_eq!(REPRESENTATIONS, [UNKNOWN, PACKET, RESOURCE]);
    assert_eq!(VALID_METHODS, [OPPORTUNISTIC, DIRECT, PROPAGATED, PAPER]);
    assert_eq!(UNVERIFIED_REASONS, [SOURCE_UNKNOWN, SIGNATURE_INVALID]);
    assert_eq!(stamper::WORKBLOCK_EXPAND_ROUNDS, 3000);
    assert_eq!(stamper::WORKBLOCK_EXPAND_ROUNDS_PN, 1000);
    assert_eq!(stamper::WORKBLOCK_EXPAND_ROUNDS_PEERING, 25);
    assert_eq!(stamper::STAMP_SIZE, 32);
}

#[tokio::test]
async fn router_ingests_python_style_propagation_transfer() {
    // Build a propagation transfer container exactly like the Python
    // propagation node client would, with a locally generated PN stamp.
    let g = golden();
    let source = fixed_identity(g["identities"]["source"]["private_hex"].as_str().unwrap());
    let destination_identity =
        fixed_identity(g["identities"]["destination"]["private_hex"].as_str().unwrap());
    let destination_public = *destination_identity.as_identity();
    let destination_hash = delivery_destination_hash(&destination_public);

    let mut message = LXMessage::new(
        destination_hash,
        delivery_destination_hash(source.as_identity()),
        b"Propagated",
        b"Propagated message",
    );
    message.destination_identity = Some(destination_public);
    message.timestamp = Some(1735689600.5);
    message
        .pack_propagation(&source, OsRng)
        .expect("pack propagation");
    assert_eq!(message.method, PROPAGATED);

    let lxmf_data = propagation_container_lxmf_data(message.propagation_packed.as_ref().unwrap());

    // Generate a PN stamp at the node's minimum accepted cost (8 - 3 = 5)
    let (stamp, value) = stamper::generate_stamp_with_rounds(
        message.transient_id.as_ref().unwrap().as_slice(),
        8,
        stamper::WORKBLOCK_EXPAND_ROUNDS_PN,
        &mut OsRng,
    );
    let stamp = stamp.expect("pn stamp");
    assert!(value >= 8);

    let mut transient_data = lxmf_data.clone();
    transient_data.extend_from_slice(&stamp);

    let mut container = Vec::new();
    FieldValue::Array(vec![
        FieldValue::F64(1735689600.5),
        FieldValue::Array(vec![FieldValue::Bin(transient_data)]),
    ])
    .pack(&mut container);

    // Router with delivery identity for the message destination
    let storage = std::env::temp_dir().join(format!(
        "lxmf-golden-propagation-{}",
        std::process::id()
    ));
    let transport = Transport::new(TransportConfig::new(
        "test-pn-ingest",
        &destination_identity,
        false,
    ));
    let router = LxmRouter::new(
        transport,
        destination_identity,
        &storage,
        Some("Test Node"),
        Some(DeliveryConfig::default()),
        RouterConfig {
            propagation_stamp_cost: 8,
            propagation_stamp_cost_flexibility: 3,
            ..Default::default()
        },
    )
    .await;

    let mut events = router.subscribe();
    let accepted = router
        .handle_propagation_transfer(&container)
        .await
        .expect("transfer handled");
    assert_eq!(accepted, 1);

    let event = tokio::time::timeout(std::time::Duration::from_secs(5), events.recv())
        .await
        .expect("event within timeout")
        .expect("event");
    match event {
        LxmEvent::Received(received) => {
            // The source identity was never announced to this router, so
            // the message is delivered with an unverified signature, exactly
            // as the Python reference implementation does.
            assert!(!received.signature_validated);
            assert_eq!(received.unverified_reason, Some(SOURCE_UNKNOWN));
            assert_eq!(received.content, b"Propagated message");
            assert_eq!(received.method, PROPAGATED);
        }
        other => panic!("expected Received event, got {other:?}"),
    }

    // A second identical transfer is still "accepted" at the stamp
    // validation level (as in the Python propagation packet handler), but
    // the message itself is deduplicated by transient id and message hash.
    let accepted_again = router
        .handle_propagation_transfer(&container)
        .await
        .expect("transfer handled");
    assert_eq!(accepted_again, 1);

    // ... but no new delivery event is emitted: the duplicate is dropped at
    // the transient-id level, exactly as the Python implementation does
    // when no duplicate signal is configured.
    assert!(events.try_recv().is_err());

    let _ = std::fs::remove_dir_all(&storage);
}
